language: php
php:
  - 5.4
env:
  - SYSTEM=TRAVIS
install:
  - composer install
  - gem install bundler
  - bundle install
before_script:
  # run PHP server (required for tests. We only start the server if we're on Travis)
  - sh deploy/server.sh --background
  # remove any existing database and create our databases
  - rm -f data/test.db
  - rm -f data/production.db
  - sqlite3 data/test.db < data/db.sql
  - sqlite3 data/production.db < data/db.sql
  # populate the test and production databases
  - php data/fixtures/seed.php test
  - php data/fixtures/seed.php production
script:
  # run our unit tests
  - ./vendor/phpunit/phpunit/phpunit test/unit_tests/
  # run our integration tests
  - cucumber features/
