language: php
php:
  - 5.4
install:
  - composer install
script:
  # create our databases
  - sqlite3 data/production.db < data/db.sql
  # populate the test database
  - php data/fixtures/seed.php
  # run our unit tests
  - ./vendor/phpunit/phpunit/phpunit test/unit_tests/
  # run our integration tests
  - cucumber features/