language: php
php:
  - 5.4
install:
  - composer install
script:
  # create our databases
  - sqlite3 data/production.db < data/db.sql 
  - sqlite3 data/test.db < data/db.sql 
  # populate the test database
  - php test/seed.php
  # run our tests
  - ./vendor/phpunit/phpunit/phpunit test/unit_tests/