language: php
php:
  - 5.4
env:
  - SYSTEM=TRAVIS
install:
  - composer install
  - export PATH=./vendor/bin:$PATH
  - gem install bundler
  - bundle install
before_script:
  # run PHP server (required for tests)
  - sh deploy/server.sh --background
  # remove any existing database and create our databases
  - rm -f data/test.db
  - rm -f data/production.db
  - sqlite3 data/test.db < data/db.sql
  - sqlite3 data/production.db < data/db.sql
  # populate the test and production databases
  - php data/fixtures/seed.php test
  - php data/fixtures/seed.php production
script:
  - phpunit test
  - cucumber features/
