language: php
php:
  - 5.4
install:
  - composer install
  - gem install bundler
  - bundle install
before_script:
  # start a web server. See http://knpuniversity.com/screencast/question-answer-day/travis-ci
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  - sudo sed -i -e "s,/var/www,$(pwd)/webapp,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart
script:
  # create our databases
  - sqlite3 data/production.db < data/db.sql
  # populate the test database
  - php data/fixtures/seed.php
  # run our unit tests
  - ./vendor/phpunit/phpunit/phpunit test/unit_tests/
  # run our integration tests
  - cucumber features/