language: php
php:
  - 5.4
install:
  - composer install
  - gem install bundler
  - bundle install
script:
  # create our databases
  - sqlite3 data/production.db < data/db.sql
  # populate the test database
  - php data/fixtures/seed.php
  # run our unit tests
  - ./vendor/phpunit/phpunit/phpunit test/unit_tests/
  # start our server
  - php -S 127.0.0.1:8000 -t webapp > /dev/null
  # run our integration tests
  - cucumber features/